version: '3.8'

services:
  qbittorrent:
    build: .  # Builds the image using the Dockerfile in the same directory
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"  # Web UI
      - "6881:6881"  # Torrent traffic (TCP)
      - "6881:6881/udp"  # Torrent traffic (UDP)
    volumes:
      - ./downloads:/downloads  # Folder for downloaded files
      - ./data:/data  # Additional persistent data storage
      - ./config/qBittorrent:/root/.config/qBittorrent  # Map qBittorrent config to host
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["qbittorrent-nox", "--webui-port=8080"]