version: '3.8'

services:
  qbittorrent:
    build: .  # Builds the image using the Dockerfile in the same directory
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:wireguard"  # Use WireGuard's network stack
    depends_on:
      - wireguard  # Ensure WireGuard starts first
    volumes:
      - ./downloads:/downloads  # Folder for downloaded files
      - ./data:/data  # Additional persistent data storage
      - ./data/qBittorrent:/root/.config/qBittorrent  # Map qBittorrent config to host
    environment:
      - DEBIAN_FRONTEND=noninteractive

  wireguard:
    container_name: wireguard
    image: jordanpotter/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - ./config/wireguard/wg0.conf:/etc/wireguard/wg0.conf
    restart: unless-stopped
    ports:
      - "8080:8080"  # Expose port 8080 for qBittorrent Web UI
      - "6881:6881"  # Expose port 6881 for torrenting (TCP)
      - "6881:6881/udp"  # Expose port 6881 for torrenting (UDP)

#  curl:
#    image: curlimages/curl
#    command: ifconfig.io
#    network_mode: service:wireguard
#    depends_on:
#      - wireguard