version: '3.8'

services:
  wireguard:
    container_name: wireguard
    build: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - ./wireguard:/etc/wireguard
      - ./downloads:/downloads  # Folder for downloaded files
      - ./data:/data  # Additional persistent data storage
      - ./data/qBittorrent:/root/.config/qBittorrent  # Map qBittorrent config to host
    ports:
      - "8080:8080"  # Expose port 8080 for qBittorrent Web UI
      - "6881:6881"  # Expose port 6881 for torrenting (TCP)
      - "6881:6881/udp"  # Expose port 6881 for torrenting (UDP)
    restart: unless-stopped

  curl:
    image: curlimages/curl
    command: ifconfig.io
    network_mode: service:wireguard
    depends_on:
      - wireguard